SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vwCRMProcess_UpdateGUIDs_ProdCopyAccount]
AS

SELECT DISTINCT  b.SSID id, b.SSB_CRMSYSTEM_ACCT_ID [SSB_CRMSYSTEM_ACCT_ID__c]
FROM dbo.vwDimCustomer_ModAcctId b
INNER JOIN ProdCopy.vw_account c WITH(NOLOCK) ON b.SSID = CAST(c.id AS VARCHAR(50))
WHERE c.[SSB_CRMSYSTEM_ACCT_ID__c] IS NULL OR c.[SSB_CRMSYSTEM_ACCT_ID__c] <> b.[SSB_CRMSYSTEM_ACCT_ID]


GO
